Repository Book-Study-For-Developer/Functional-coding-that-fits-easily, pull requests merged in 2024-08, with the labels that each got.

#5 docs: 1장, 2장 정리
  장수민/01. 쏙쏙 들어오는 함수형 코딩에 오신 것을 환영합니다/README.md
  장수민/02. 함수형 사고/README.md
Labels: 1회차

#12 docs: [08/22 스터디 2회차] 3, 4장 정리
  고석영/03. 액션과 계산, 데이터의 차이를 알기/README.md
  고석영/04. 액션에서 계산 빼내기/README.md
  고석영/README.md
Labels: 2회차

#7 docs: [08/22 스터디 2회차] 3, 4장 정리
  하현준/03. 액션과 계산, 데이터의 차이를 알기/README.md
  하현준/04. 액션에서 계산빼내기/README.md
Labels: 2회차

#9 docs: [08/22 스터디 2회차] 3, 4장 정리
  조성환/03. 액션과 계산, 데이터의 차이를 알기/README.md
  조성환/04. 액션에서 계산 빼내기/README.md
Labels: 2회차

#11 docs: [08/22 스터디 2회차] 3, 4장 정리
  장수민/03. 액션과 계산, 데이터의 차이를 알기/README.md
  장수민/03. 액션과 계산, 데이터의 차이를 알기/헬스장 가기 타임라인.png
  장수민/04. 액션에서 계산 빼내기/README.md
  장수민/05. 더 좋은 액션 만들기/README.md
  장수민/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 2회차, 발표자

#10 docs: [08/22 스터디 2회차] 3, 4장 정리
  김서현/03. 액션과 계산, 데이터의 차이를 알기/README.md
  김서현/04. 액션에서 계산 빼내기/README.md
Labels: 2회차

#17 remove: main 브랜치에 병합된 5, 6장 정리 내용 삭제
  장수민/05. 더 좋은 액션 만들기/README.md
  장수민/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차

#8 docs: [08/22 스터디 2회차] 3, 4장 정리
  이지수/03. 액션과 계산, 데이터의 차이를 알기/README.md
  이지수/04. 액션에서 계산 빼내기/README.md
Labels: 2회차

#15 docs: [08/29 스터디 3회차] 5, 6장 정리
  하현준/05. 더 좋은 액션 만들기/README.md
  하현준/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차
