Repository Book-Study-For-Developer/Functional-coding-that-fits-easily, pull requests merged in 2024-09, with the labels that each got.

#20 docs: [08/29 스터디 3회차] 5, 6장 정리
  이지수/05. 더 좋은 액션 만들기/README.md
  이지수/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차

#21 docs: [08/29 스터디 3회차] 5, 6장 정리
  김서현/05. 더 좋은 액션 만들기/README.md
  김서현/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차

#19 docs: [08/29 스터디 3회차] 5, 6장 정리
  장수민/05. 더 좋은 액션 만들기/README.md
  장수민/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차

#16 docs: [08/29 스터디 3회차] 5, 6장 정리
  조성환/05. 더 좋은 액션 만들기/README.md
  조성환/06. 변경 가능한 데이터 구조를 가진 언어에서 불변성 유지하기/README.md
Labels: 3회차

#24 docs: [09/05 스터디 4회차] 7, 8장 내용 정리
  이지수/07. 신뢰할 수 없는 코드를 쓰면서 불변성 지키기/README.md
  이지수/08. 계층형 설계 I/README.md
Labels: 4회차

#25 docs: [09/05 스터디 4회차] 7, 8장 내용 정리
  장수민/07. 신뢰할 수 없는 코드를 쓰면서 불변성 지키기/README.md
  장수민/08. 계층형 설계 I/README.md
  장수민/08. 계층형 설계 I/fp-8-1.png
  장수민/08. 계층형 설계 I/fp-8-2.png
  장수민/08. 계층형 설계 I/fp-8-3.png
  장수민/08. 계층형 설계 I/fp-8-4.png
Labels: 4회차, 발표자

#26 docs: [09/05 스터디 4회차] 7, 8장 내용 정리
  고석영/07. 신뢰할 수 없는 코드를 쓰면서 불변성 지키기/README.md
  고석영/08. 계층형 설계 1/README.md
  고석영/README.md
Labels: 4회차

#28 docs: [09/05 스터디 4회차] 7, 8장 내용 정리
  조성환/07. 신뢰할 수 없는 코드를 쓰면서 불변성 지키지/README.md
  조성환/08. 계층형 설계1/README.md
  조성환/08. 계층형 설계1/img/image1.png
  조성환/08. 계층형 설계1/img/image2.png
  조성환/08. 계층형 설계1/img/image3.png
  조성환/08. 계층형 설계1/img/image4.png
Labels: 4회차

#27 docs: [09/05 스터디 4회차] 7, 8장 내용 정리
  김서현/07. 신뢰할 수 없는 코드를 쓰면서 불변성 지키기/README.md
  김서현/08. 계층형 설계 1/README.md
Labels: 4회차

#29 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  하현준/09. 계층형 설계 Ⅱ/README.md
  하현준/10. 일급 함수 Ⅰ/README.md
  하현준/11. 일급 함수 Ⅱ/README.md
Labels: 5회차

#33 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  장수민/09. 계층형 설계 II/README.md
  장수민/10. 일급 함수 I/README.md
  장수민/11. 일급 함수 II/README.md
Labels: 5회차

#31 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  조성환/09. 계층형 설계2/README.md
  조성환/09. 계층형 설계2/img/image1.png
  조성환/09. 계층형 설계2/img/image2.png
  조성환/10. 일급함수1/README.md
  조성환/11. 일급함수2/README.md
Labels: 5회차

#34 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  김서현/09. 계층형 설계 2/README.md
  김서현/10. 일급 함수 1/README.md
  김서현/11. 일급 함수 2/README.md
Labels: 5회차, 발표자

#32 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  이지수/09. 계층형 설계 II/README.md
  이지수/10. 일급 함수 I/README.md
  이지수/11. 일급 함수 II/README.md
Labels: 5회차, 발표자

#30 docs: [09/19 스터디 5회차] 9, 10, 11장 내용 정리
  고석영/09. 계층형 설계 2/README.md
  고석영/10. 일급 함수 1/README.md
  고석영/11. 일급 함수 2/README.md
  고석영/README.md
Labels: 5회차
